spring:
  datasource:
    url: jdbc:mysql://localhost/access_thymeleaf
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
    database-platform: org.hibernate.dialect.MySQLDialect

  session:
    jdbc:
      initialize-schema: always

server:
  port: 8909
